# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(blank=True, max_length=20, verbose_name='slack team id')),
                ('team_name', models.CharField(blank=True, max_length=100, verbose_name='slack team name')),
                ('access_token', models.CharField(blank=True, max_length=50, verbose_name='slack access token')),
                ('bot_name', models.CharField(blank=True, max_length=30, verbose_name='slack bot id')),
                ('bot_token', models.CharField(blank=True, max_length=50, verbose_name='slack bot token')),
                ('error_channel', models.CharField(blank=True, help_text='The channel where Django error posts go, and also acts as the default channel.', max_length=20, verbose_name='slack error channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
