# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackintegration',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='slack access token'),
        ),
        migrations.AlterField(
            model_name='slackintegration',
            name='bot_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='slack bot token'),
        ),
    ]
